name       : pixman
version    : 0.34.0
release    : 9
source     :
    - http://xorg.freedesktop.org/releases/individual/lib/pixman-0.34.0.tar.gz : 21b6b249b51c6800dc9553b65106e1e37d0e25df942c90531d4c3997aa20a88e
license    :
    - MIT
summary    : pixman (software library for pixel manipulation)
component  : desktop.library
builddeps  :
    - pkgconfig32(libpng15)
    - glibc-32bit-devel
    - libgcc-32bit
optimize   : speed
emul32     : yes
description: |
    pixman is a low-level software library for pixel manipulation, providing features such as image compositing.
setup      : |
    %configure --prefix=/usr --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
profile    : |
    %make check
