name        : pixman
version     : 0.32.0
release     : 5
source      :
    - http://cairographics.org/releases/pixman-0.32.0.tar.gz : 310b8d07160db7034a17a09de4c3fad34ea5ae1327f9d81dbcb54cffca26c14a
homepage    : http://ww.pixman.org
license     :
    - MIT
summary     : pixman (software library for pixel manipulation)
builddeps   :
    - pkgconfig(libpng15)
description : |
    pixman is a low-level software library for pixel manipulation, providing features such as image compositing.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    %make clean
