name       : pixman
version    : 0.38.4
release    : 11
source     :
    - http://xorg.freedesktop.org/releases/individual/lib/pixman-0.38.4.tar.gz : da66d6fd6e40aee70f7bd02e4f8f76fc3f006ec879d346bae6a723025cfbdde7
license    :
    - MIT
summary    : pixman (software library for pixel manipulation)
component  : desktop.library
builddeps  :
    - glibc-32bit-devel
    - libgcc-32bit
    - libgomp-32bit
    - libpng15
rundeps    :
    - gtk+-2.0
    - libpng
optimize   : speed
emul32     : yes
description: |
    pixman is a low-level software library for pixel manipulation, providing features such as image compositing.
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
profile    : |
    %ninja_check
